<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/08/11 17:30:23

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=onehr_mysql',
  'username' => 'onehr_admin',
  'password' => NULL,
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
